server:
  host: "0.0.0.0"
  port: 8000
  debug: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

target:
  url: "http://localhost:3001"
  headers:
    X-Proxy-Source: "debug-proxy"
  endpoints:
    - path: "/api/users"
      methods: ["GET", "POST", "PUT", "DELETE"]
      debug: true
      failure_rules:
        - condition:
            enabled: true
            method: "POST"
            #count: 3
            every: 1
          response:
            status_code: 503
            body: {"error": "Service temporarily unavailable"}
    - path: "/api/users/.*"
      methods: ["GET"]
      debug: true
      failure_rules:
        - condition:
            enabled: true
            method: "GET"
            probability: 0.1
          response:
            status_code: 500
            body: {"error": "Internal server error"}
        - condition:
            enabled: false  # Disabled example
            method: "GET"
            every: 10
          response:
            status_code: 429
            body: {"error": "Rate limited - every 10th request"}
    - path: "/auth/login"
      methods: ["POST"]
      debug: true
      failure_rules:
        - condition:
            enabled: true
            method: "POST"
            delay: 5000
          response:
            status_code: 408
            body: {"error": "Request timeout"}
    - path: "/*"
      methods: ["*"]
      debug: true
